import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {GraphQLClient, gql} from 'graphql-request';

const graphcms = new GraphQLClient(
  'https://api-us-west-2.hygraph.com/v2/cla9bg4tx1k0c01t55x4vh3d3/master'
);

const QUERY = gql`
  {
    posts {
      id, 
      title,
      datePublished,
      slug,
      content{
        html
      }
      author {
        name,
        avatar{
          url
        }
      }
      coverPhoto{
        publishedAt{
          createdBy{
            id
          }
          url
        }
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
  };
}

export default function Home() {



  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      </main>

    </div>
  )
}
